### ISSUE TITLE
Installing QIIME1.9X with Anaconda2

### ISSUE THREAD

**Issue by Owen-haha** [biocore/qiime#2108] opened 2015-11-20 06:44 UTC
Dear QIIME,
I want to install QIIME on the Linux cluster without root authority. I try to install with Anaconda2. 
Following is my installing steps:
1. Download and install Anaconda2-2.4.0 on my personal directory,
2. Run command "bin/conda install -c https://conda.anaconda.org/jorge qiime " under the Anaconda directory.
I did not receive any ERROR message during the installation. However, when I try to run "./Anaconda2-2.4.0/bin/python2.7 bin/align_seqs.py" I got the ERROR message that "pkg_resources.DistributionNotFound: The 'mock' distribution was not found and is required by matplotlib".
How can I correctly install the QIIME using Anaconda2 without root authority? 

######The detail of error message
Traceback (most recent call last):
  File "bin/align_seqs.py", line 4, in <module>
    __import__('pkg_resources').run_script('qiime==1.9.0rc2', 'align_seqs.py')
  File "/ifs4/BC_PUB/biosoft/pipeline/Package/Anaconda2-2.4.0/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py", line 3080, in <module>
  File "/ifs4/BC_PUB/biosoft/pipeline/Package/Anaconda2-2.4.0/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py", line 3066, in _call_aside
  File "/ifs4/BC_PUB/biosoft/pipeline/Package/Anaconda2-2.4.0/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py", line 3093, in _initialize_master_working_set
  File "/ifs4/BC_PUB/biosoft/pipeline/Package/Anaconda2-2.4.0/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py", line 653, in _build_master
  File "/ifs4/BC_PUB/biosoft/pipeline/Package/Anaconda2-2.4.0/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py", line 666, in _build_from_requirements
  File "/ifs4/BC_PUB/biosoft/pipeline/Package/Anaconda2-2.4.0/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py", line 839, in resolve
pkg_resources.DistributionNotFound: The 'mock' distribution was not found and is required by matplotlib

###### The detail of installation log information
bin/conda install -c https://conda.anaconda.org/jorge qiime
Fetching package metadata: ......
Solving package specifications: .........................................
Package plan for installation in environment /ifs4/BC_PUB/biosoft/pipeline/Package/Anaconda2-2.4.0:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mpich2-1.4.1p1             |                0         2.6 MB
    future-0.14.3              |           py27_0         609 KB
    gdata-2.0.18               |           py27_0         764 KB
    mpi4py-1.3.1               |           py27_0         1.3 MB
    natsort-3.5.0              |           py27_0          26 KB
    numpy-1.9.3                |           py27_0         5.7 MB
    pytz-2015.7                |           py27_0         174 KB
    qcli-0.1.1                 |           py27_0          16 KB
    qiime-default-reference-0.1.1|           py27_0        20.1 MB
    burrito-0.9.0              |           py27_0          61 KB
    conda-3.18.6               |           py27_0         176 KB
    pyqi-0.3.2                 |           py27_0          57 KB
    scipy-0.16.0               |       np19py27_1        28.2 MB
    biom-format-2.1.2          |           py27_0         343 KB
    pandas-0.16.2              |       np19py27_0        10.8 MB
    matplotlib-1.4.3           |       np19py27_2        44.5 MB
    cogent-1.5.3               |       np19py27_0         2.3 MB
    scikit-bio-0.2.3           |       np19py27_0         947 KB
    burrito-fillings-0.1.0     |           py27_0         484 KB
    emperor-0.9.5              |           py27_0         396 KB
    pynast-1.2.2               |           py27_0          28 KB
    qiime-1.9.0.dev            |           py27_0        12.0 MB
    ------------------------------------------------------------
                                           Total:       131.5 MB

The following NEW packages will be INSTALLED:

    biom-format:             2.1.2-py27_0     
    burrito:                 0.9.0-py27_0     
    burrito-fillings:        0.1.0-py27_0     
    cogent:                  1.5.3-np19py27_0 
    emperor:                 0.9.5-py27_0     
    future:                  0.14.3-py27_0    
    gdata:                   2.0.18-py27_0    
    mpi4py:                  1.3.1-py27_0     
    mpich2:                  1.4.1p1-0        
    natsort:                 3.5.0-py27_0     
    pynast:                  1.2.2-py27_0     
    pyqi:                    0.3.2-py27_0     
    qcli:                    0.1.1-py27_0     
    qiime:                   1.9.0.dev-py27_0 
    qiime-default-reference: 0.1.1-py27_0     
    scikit-bio:              0.2.3-np19py27_0 

The following packages will be UPDATED:

    conda:                   3.18.3-py27_0      --> 3.18.6-py27_0    
    matplotlib:              1.4.3-np110py27_2  --> 1.4.3-np19py27_2 
    pytz:                    2015.6-py27_0      --> 2015.7-py27_0    
    scipy:                   0.16.0-np110py27_1 --> 0.16.0-np19py27_1

The following packages will be DOWNGRADED:

    numpy:                   1.10.1-py27_0      --> 1.9.3-py27_0     
    pandas:                  0.17.0-np110py27_0 --> 0.16.2-np19py27_0

Proceed ([y]/n)? y

Fetching packages ...
mpich2-1.4.1p1 100% |###############################################################################################################| Time: 0:00:04 651.06 kB/s
future-0.14.3- 100% |###############################################################################################################| Time: 0:00:02 268.56 kB/s
gdata-2.0.18-p 100% |###############################################################################################################| Time: 0:00:02 337.42 kB/s
mpi4py-1.3.1-p 100% |###############################################################################################################| Time: 0:00:02 493.79 kB/s
natsort-3.5.0- 100% |###############################################################################################################| Time: 0:00:00 113.33 kB/s
numpy-1.9.3-py 100% |###############################################################################################################| Time: 0:00:06 887.04 kB/s
pytz-2015.7-py 100% |###############################################################################################################| Time: 0:00:01 152.31 kB/s
qcli-0.1.1-py2 100% |###############################################################################################################| Time: 0:00:00  33.00 kB/s
qiime-default- 100% |###############################################################################################################| Time: 0:00:13   1.52 MB/s
burrito-0.9.0- 100% |###############################################################################################################| Time: 0:00:00 132.56 kB/s
conda-3.18.6-p 100% |###############################################################################################################| Time: 0:00:01 153.50 kB/s
pyqi-0.3.2-py2 100% |###############################################################################################################| Time: 0:00:01  42.30 kB/s
scipy-0.16.0-n 100% |###############################################################################################################| Time: 0:00:32 899.03 kB/s
biom-format-2. 100% |###############################################################################################################| Time: 0:00:01 245.31 kB/s
pandas-0.16.2- 100% |###############################################################################################################| Time: 0:00:15 743.33 kB/s
matplotlib-1.4 100% |###############################################################################################################| Time: 0:58:09  13.38 kB/s
cogent-1.5.3-n 100% |###############################################################################################################| Time: 0:00:03 773.02 kB/s
scikit-bio-0.2 100% |###############################################################################################################| Time: 0:00:03 322.48 kB/s
burrito-fillin 100% |###############################################################################################################| Time: 0:00:01 301.40 kB/s
emperor-0.9.5- 100% |###############################################################################################################| Time: 0:00:04  82.10 kB/s
pynast-1.2.2-p 100% |###############################################################################################################| Time: 0:00:00  37.33 kB/s
qiime-1.9.0.de 100% |###############################################################################################################| Time: 0:00:12   1.05 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|######################################################################################################################| 100%

**Comment by colinbrislawn** [comment] 2015-12-03 21:28
Hello @Owen-haha,

I think you are on the right track. I would modify your process in two small ways:
 1. Install as many packages as possible using conda.
 2. Install qiime from the git archive (instead of jorge's old anaconda package).

Try this:
```
conda info -e
conda -n create qiime191 pip numpy matplotlib IPython future natsort scipy pandas scikit-bio gdata h5py
source activate qiime191
pip install https://github.com/biocore/qiime/archive/1.9.1.tar.gz
```

**Comment by Owen-haha** [comment] 2015-12-04 03:11
Thank you very much @colinbrislawn !
pip installation works well for me.

**Comment by colinbrislawn** [comment] 2016-02-02 20:54
@Owen-haha Good to hear that it worked! Can you close this issue?

**Comment by bgruening** [comment] 2016-03-02 07:46
There is now a qiime package in bioconda. Please try `conda create qiime -c bioconda`.

**Comment by gregcaporaso** [comment] 2016-03-18 17:05
This is now working for me, thanks again @bgruening! 

Is this issue ready to be closed?

**Comment by bgruening** [comment] 2016-03-18 17:16
@gregcaporaso great! Now we need to finish the Galaxy integration :)

**Comment by gregcaporaso** [comment] 2016-03-18 17:27
@bgruening, Galaxy integration may be better saved for QIIME 2, as it'll be a lot easier (and that will be conda-installable by design).

**Closed** 2016-03-18 17:27 UTC

**Comment by bgruening** [comment] 2016-03-18 17:31
@gregcaporaso how long will this take? We have a few users that are eager to use it :)

**Comment by gregcaporaso** [comment] 2016-03-18 17:37
You can find some info in my [Toward QIIME 2](https://qiime.wordpress.com/2015/10/30/toward-qiime-2/) blog post - we're still in pretty good shape with respect to the schedule presented there. I don't want to dissuade you from working on it, but it has been attempted before and it's not going to be easy (you should discuss with @josenavas if you are interested in doing this). I think it's likely a better use of time to hold off for QIIME 2.

**Comment by bgruening** [comment] 2016-03-18 17:41
Ok thanks for the info. We are in contact and now joining forces in a community effort to create these wrappers. https://github.com/galaxyproject/tools-iuc/pull/431

**Comment by gregcaporaso** [comment] 2016-03-18 17:43
Ok, just wanted to make sure you were aware of our progress toward QIIME 2. Thanks for all of your efforts, we really appreciate it!
