### ISSUE TITLE
Error messages when normalizing with DESeq2 and CSS

### ISSUE THREAD

**Issue by kathfi** [biocore/qiime#2159] opened 2016-07-07 11:17 UTC
Dear Greg,

unfortunately I am not allowed to post in the Google forum you indicated for the issue above - maybe it is possible to address it here, or give instructions how to join the forum?

many thanks
Katharina

**Comment by gregcaporaso** [comment] 2016-07-07 15:34
Duplicate of #2157.

**Closed by gregcaporaso** 2016-07-07 15:34 UTC
