### ISSUE TITLE
Matplotlib compatability issue

### ISSUE THREAD

**Issue by JWDebelius** [biocore/qiime#2132] opened 2016-02-22 22:49 UTC
We've had two rotation students here run into issues with recent (in the past few weeks) with matplotlib in recent (past few weeks) installations on our super computer. The error is complain about plotting multiple things on the same axis; It seems to be solved by installing 1.4 or so.

Should the pip installation limit the version of matplotlib installed?

**Comment by cdiener** [comment] 2016-03-04 18:55
This is a duplicate of #2117. Qiime 1.9.1 does not play well with matplotlib 1.5 due to the matplotlib API changes.

**Comment by gregcaporaso** [comment] 2016-03-18 17:10
Closing this one in favor of #2117, as there is more detail in that issue.

**Closed by gregcaporaso** 2016-03-18 17:10 UTC
