### ISSUE TITLE
R scripts error on biom files encoded with hdf5

### ISSUE THREAD

**Issue by mlangill** [biocore/qiime#1928] opened 2015-02-05 15:21 UTC
I was testing out the new **normalize_table.py** script and kept getting a cryptic error message (see below). This was due to the biom file being encoded in hdf5 instead of json. I'm not sure if new versions of the R biom package will be able to handle the hdf5 encoding, but for now it would be better to give a better error message so the user knows to convert their biom file to json format. 

```
command: cd "/home/mlangill/Dropbox/work/projects/andy/";  R --slave --args --source_dir /home/mlangill/.virtualenvs/qiime1.9/local/lib/python2.7/site-packages/qiime/support_files/R -i /tmp/QIIME-normalize-table-temp-table-Syqq2D.biom -o final_otu_tables/otu_table_css_norm.biom  < /home/mlangill/.virtualenvs/qiime1.9/local/lib/python2.7/site-packages/qiime/support_files/R/CSS.r
stdout:

stderr:
Error in if (!object$type %in% biomtypevals) { : 
  argument is of length zero
Calls: CSS ... initialize -> validObject -> anyStrings -> validityMethod
Execution halted
```

**Comment by jairideout** [comment] 2015-02-05 16:04
Thanks for reporting this @mlangill! I thought normalize_table.py was supposed to handle JSON and HDF5 files (it creates a temporary JSON file if the input is HDF5). @sowe9385 can you please take a look?

**Comment by alk224** [comment] 2015-02-05 19:56
I get a similar error (see below).  If I use a table produced in qiime 1.8 (json) I don't get this error.

normalize_table.py -i cdhit_otus/raw_otu_table.biom -o cdhit_otus/raw_otu_table_CSS.biom -a CSS
Traceback (most recent call last):
  File "/usr/local/bin/normalize_table.py", line 142, in <module>
    main()
  File "/usr/local/bin/normalize_table.py", line 125, in main
    normalize_CSS(input_path, out_path, output_CSS_statistics)
  File "/usr/local/lib/python2.7/dist-packages/qiime/normalize_table.py", line 38, in normalize_CSS
    run_CSS(temp_fh.name, out_path, output_CSS_statistics=output_CSS_statistics)
  File "/usr/local/lib/python2.7/dist-packages/qiime/normalize_table.py", line 76, in run_CSS
    app_result = rsl(command_args=command_args, script_name='CSS.r')
  File "/usr/local/lib/python2.7/dist-packages/qiime/util.py", line 1946, in __call__
    (exit_status, command, stdout, stderr))
burrito.util.ApplicationError: Unacceptable application exit status: 1
command: cd "/home/enggen/Desktop/TestDataSets/16Smock/6kdata/";  R --slave --args --source_dir /usr/local/lib/python2.7/dist-packages/qiime/support_files/R -i /tmp/QIIME-normalize-table-temp-table-RlGR3C.biom -o cdhit_otus/raw_otu_table_CSS.biom  < /usr/local/lib/python2.7/dist-packages/qiime/support_files/R/CSS.r
stdout:

stderr:
Error in if (!object$type %in% biomtypevals) { : 
  argument is of length zero
Calls: CSS ... initialize -> validObject -> anyStrings -> validityMethod
Execution halted

**Comment by wasade** [comment] 2015-02-05 20:00
It looks like either QIIME 1.9 or BIOM 2.1.3 is improperly specifying the
table type. I'm seeing the following in the JSON files:

"type": null

Which would correspond with the error being produced

**Comment by alk224** [comment] 2015-02-05 20:10
I have biom-format 2.1.2 if it matters.

**Comment by sowe9385** [comment] 2015-02-06 00:26
@mlangill can you please detail how this .biom table was created?  Did you use make_otu_table.py? Thanks.

**Comment by alk224** [comment] 2015-02-06 00:39
Sophie emailed me that if she runs biom convert to specifically change my table to hdf5 or json it will normalize fine.  I confirmed this is the case.  Certainly a workaround for now, but puzzling make_otu_table is yielding something else for at least a couple of us.

enggen@OptimusPrime:~/Desktop/TestDataSets/16Smock/6kdata$ biom convert -i cdhit_otus/raw_otu_table.biom -o cdhit_otus/raw_otu_table_fixed.biom --table-type="OTU table" --to-hdf5
enggen@OptimusPrime:~/Desktop/TestDataSets/16Smock/6kdata$ normalize_table.py -i cdhit_otus/raw_otu_table_fixed.biom -o cdhit_otus/raw_otu_table_CSS.biom -a CSS
enggen@OptimusPrime:~/Desktop/TestDataSets/16Smock/6kdata$ ls -l cdhit_otus
total 1332
drwxrwxr-x 2 enggen enggen    4096 Feb  5 13:12 blast_taxonomy_assignment
-rw-rw-r-- 1 enggen enggen 1171957 Feb  5 13:11 merged_otu_map.txt
-rw-rw-r-- 1 enggen enggen   18658 Feb  5 13:11 merged_rep_set.fna
-rw-rw-r-- 1 enggen enggen     211 Feb  5 13:11 prefix_rep_set_otus.log
-rw-rw-r-- 1 enggen enggen    8864 Feb  5 13:11 prefix_rep_set_otus.txt
drwxrwxr-x 2 enggen enggen    4096 Feb  5 13:11 pynast_aligned_seqs
-rw-rw-r-- 1 enggen enggen   55520 Feb  5 13:12 raw_otu_table.biom
-rw-rw-r-- 1 enggen enggen   21447 Feb  5 17:32 raw_otu_table_CSS.biom
-rw-rw-r-- 1 enggen enggen   55520 Feb  5 17:32 raw_otu_table_fixed.biom
-rw-rw-r-- 1 enggen enggen     634 Feb  5 13:12 raw_otu_table.summary

**Comment by mlangill** [comment] 2015-02-06 01:26
My OTU table was created with pick_open_reference_otus.py back when it was creating hdf5 biom files by default, before this bug: https://github.com/biocore/qiime/issues/1849

I assumed it was an hdf5 problem because when I converted it to json it solved the problem. Didn't test with another hdf5 biom file.

**Closed** 2015-04-30 00:07 UTC
Labels: bug

**Comment by natassagioti** [comment] 2015-09-16 07:18
Hi, 
I get a related error in macqiime 1.9, and creating the biom file with macqiime 1.8 doesnot solve the problem:
normalize_table.py --input_path=/Users/natassa/Hypoxia/seqdata/AnalysisB/TrimmedFiltered/bioms/23718/Archaea182_qiime1.8.biom  --algorithm=CSS --out_path=$biompath/Archaea182_CSS2.biom
Traceback (most recent call last):
  File "/macqiime/anaconda/bin/normalize_table.py", line 157, in <module>
    main()
  File "/macqiime/anaconda/bin/normalize_table.py", line 140, in main
    normalize_CSS(input_path, out_path, output_CSS_statistics)
  File "/macqiime/anaconda/lib/python2.7/site-packages/qiime/normalize_table.py", line 38, in normalize_CSS
    run_CSS(temp_fh.name, out_path, output_CSS_statistics=output_CSS_statistics)
  File "/macqiime/anaconda/lib/python2.7/site-packages/qiime/normalize_table.py", line 76, in run_CSS
    app_result = rsl(command_args=command_args, script_name='CSS.r')
  File "/macqiime/anaconda/lib/python2.7/site-packages/qiime/util.py", line 1968, in __call__
    (exit_status, command, stdout, stderr))
burrito.util.ApplicationError: Unacceptable application exit status: 1
command: cd "/Users/natassa/Desktop/";  R --slave --args --source_dir /macqiime/anaconda/lib/python2.7/site-packages/qiime/support_files/R -i /tmp/QIIME-normalize-table-temp-table-kW3H4m.biom -o /Users/natassa/Hypoxia/seqdata/AnalysisB/TrimmedFiltered/bioms/23718/Archaea182_CSS2.biom  < /macqiime/anaconda/lib/python2.7/site-packages/qiime/support_files/R/CSS.r
stdout:

stderr:
Error in cumNormStatFast(obj) : Warning sample with one or zero features
Calls: CSS -> cumNormStatFast
Execution halted

I can't explain this message, any ideas?
Thanks, 
Anastasia

**Comment by sowe9385** [comment] 2015-09-16 07:48
Yes, it is a slightly different error.  Do you have samples with very low
sequences per sample?  Generally these samples (e.g. depth 300) are removed
prior to normalization.  It is telling you that you have a sample with only
one or none nonzero OTUs.  If you remove that sample, it should work.

**Comment by natassagioti** [comment] 2015-09-16 10:05
Thanks for your quick reply! 
I had indeed one such sample, deleting it solved the issue.
Best,
Anastasia

**Comment by sowe9385** [comment] 2015-09-16 10:37
Thanks for letting us know.

**Comment by richrr** [comment] 2016-08-06 17:32
Hi

This could be a new question also, but based on the relevant discussion in this thread I thought I could post it here. 

I generated a biom (1.3) file using QIIME (1.8). The last command that was run was filter_otus_from_otu_table.py. I wanted to normalize the otu table using normalize_table.py which is a qiime 1.9 function. So I tried two things: (i) using the biom file directly in qiime 1.9 (ii) converting the txt otu table to biom in qiime 1.9

Both give me errors. I tried running the biom from qiime 1.8 in R using metagenomeseq and get
> obj = cumNorm(ObjData, p = cumNormStatFast(ObjData))
Error in `[<-`(`*tmp*`, leng:(leng - length(smat[[i]]) + 1), i, value = numeric(0)) : 
  subscript out of bounds

Please help about how I can fix this.
